name: my_flutter_template_v2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ─── NETWORKING ─────────────────────────────────────────────
  http: ^1.2.2
  cached_network_image: ^3.4.0
  http_certificate_pinning: ^3.0.1
  # ─── End Networking ─────────────────────────────────────────

  # ─── STATE MANAGEMENT ──────────────────────────────────────
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.2
  get_it: ^8.0.3
  freezed_annotation: ^3.0.0
  freezed:
  equatable: ^2.0.5
  # ─── End State Management ──────────────────────────────────

  # ─── STORAGE ───────────────────────────────────────────────
  shared_preferences: ^2.3.5
  path_provider: ^2.0.9
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # ─── End Storage ───────────────────────────────────────────

  # ─── UI & UX ENHANCEMENTS ──────────────────────────────────
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.5
  another_flushbar: ^1.12.30
  flashy_flushbar:
    git:
      url: https://github.com/quiet-programmer/flashy_flushbar.git
      ref: c9af9f8
  modal_bottom_sheet: ^3.0.0-pre
  flutter_html: ^3.0.0-beta.1
  lucide_icons: ^0.257.0
  huge_icons:
    git:
      url: https://github.com/AminAhmadyDeveloper/huge_icons.git
  # ─── End UI & UX Enhancements ──────────────────────────────

  # ─── DEVICE INTEGRATION ────────────────────────────────────
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.0
  local_auth: ^2.1.7
  package_info_plus: ^8.0.0
  url_launcher: ^6.0.10
  onscreen_num_keyboard: ^1.0.4
  ai_barcode_scanner: ^6.0.1
  qr_flutter:
  onesignal_flutter: ^5.1.5
  share_plus: ^11.0.0
  drop_down_list:
    git:
      url: https://github.com/quiet-programmer/drop_down_list.git
      ref: dfb7ec1
  otp_text_field_v2: ^1.0.3
  get_time_ago: ^2.3.0
  pull_to_refresh_plus: ^2.0.3
  syncfusion_flutter_datepicker: ^29.1.38
  syncfusion_flutter_barcodes: ^29.1.38
  flutter_inappwebview: ^6.1.5
  clipboard: ^0.1.3
  # ─── End Device Integration ────────────────────────────────

  # ─── UTILITIES & MISC ──────────────────────────────────────
  logger: ^2.4.0
  yaml: ^3.1.2
  analyzer: ^6.7.0
  # ─── End Utilities & Misc ──────────────────────────────────


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.0
  build_runner: ^2.4.12

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/dev/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/
    - assets/dev/
    - assets/icons/
    - assets/svg/
    - api_credentials.yaml

  fonts:
    - family: PublicSansBlack
      fonts:
        - asset: assets/fonts/PublicSans-Black.otf

    - family: PublicSansBold
      fonts:
        - asset: assets/fonts/PublicSans-Bold.otf

    - family: PublicSansExtraBold
      fonts:
        - asset: assets/fonts/PublicSans-ExtraBold.otf

    - family: PublicSansExtraLight
      fonts:
        - asset: assets/fonts/PublicSans-ExtraLight.otf

    - family: PublicSansLight
      fonts:
        - asset: assets/fonts/PublicSans-Light.otf

    - family: PublicSansMedium
      fonts:
        - asset: assets/fonts/PublicSans-Medium.otf

    - family: PublicSansRegular
      fonts:
        - asset: assets/fonts/PublicSans-Regular.otf

    - family: PublicSansSemiBold
      fonts:
        - asset: assets/fonts/PublicSans-SemiBold.otf

    - family: PublicSansThin
      fonts:
        - asset: assets/fonts/PublicSans-Thin.otf